config/routes.rb
MAST::Application.routes.draw do



  root to: 'welcome#index'
  
  devise_for :users


  resources :users, only: [:show]
  resources :subscriptions, only: [:index, :show, :new, :create, :destroy]
  resources :destinations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :subscribe, only: [:new, :create]

  resource :cart, only: [:create, :destroy, :show] do
    put 'add/:destination_id', to: 'carts#add', as: :add_to
    put 'remove/:destination_id', to: 'carts#remove', as: :remove_from
  end
  
  resources :purchases, only: [:new, :create]





end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController

  # before_filter :authenticate_user!

  def new
  end

  def create
    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create a Customer
    customer = Stripe::Customer.create(
      :card => token,
      :plan => "001",
      :email => current_user.email
      )
    current_user.update_attribute(:role, 'subscriber')
    current_user.stripe_id = customer.id
    current_user.save
    flash[:notice] = "OK"
    redirect_to current_user

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_subscribe_path

  end

end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/views/subscribe/new.html.erb


<%= form_tag subscribe_index_path do %>
  <article>
    <label class="amount">
      <span>Amount: $10.00 a month</span>

    </label>
  </article>
  <div class="col-md-12">
    <%= render partial: 'subscriptions/itinerary' %>
  </div>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="1000"></script>
<% end %>