config/routes.rb
MAST::Application.routes.draw do



  root to: 'welcome#index'
  
  devise_for :users


  resources :users, only: [:show]
  resources :subscriptions, only: [:index, :show, :new, :create, :destroy]
  resources :destinations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :subscribe, only: [:new, :create]

  resource :cart, only: [:create, :destroy, :show] do
    put 'add/:destination_id', to: 'carts#add', as: :add_to
    put 'remove/:destination_id', to: 'carts#remove', as: :remove_from
  end
  
  resources :purchases, only: [:new, :create]





end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :user

  ################################################################
  # def self.subscription_to_destinations_key(user_id)
  #   "subscription_to_destinations_key:#{self.id.to_s}"
  # end

  # def subscription_to_destinations_key
  #   User.subscription_to_destinations_key(self.id)
  # end
  # #######################################################
  # def self.destination_to_users_key(destination_id)
  #   "destination_to_users_key:#{dest.id.to_s}"
  # end

  # def destination_to_users_key
  #   Destination.destination_to_users_key(self.id)
  # end
  #################################################################


  def add_destination(dest)
    REDIS.sadd "subscription_to_destinations_key:#{self.id.to_s}", dest.id.to_s
    REDIS.sadd "destination_to_subscriptions_key:#{dest.id.to_s}", self.id.to_s
    ######################################################
    # REDIS.sadd self.subscription_to_destinations_key, dest.id.to_s
    # REDIS.sadd dest.destination_to_subscriptions_key, self.id.to_s
  end

  def rem_destination(dest)
    REDIS.srem "subscription_to_destinations_key:#{self.id.to_s}", dest.id.to_s
    REDIS.srem "destination_to_subscriptions_key:#{dest.id.to_s}", self.id.to_s
  end

  def destinations
    array_destination_ids = REDIS.smembers "subscription_to_destinations_key:#{self.id.to_s}"
    return Destination.where(id: array_destination_ids)
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  # before_filter :authenticate_user!

  def index
  end

  def show
    @subscription = Subscription.find(params[:id])
    @destinations = @subscription.destinations
  end

  def new
    @subscription = Subscription.new
  end

  def create 
    @subscription = current_user.subscriptions.build(subscription_params)

    # dest = Destination.find_by_chronological_order(1)
    # @subscription.add_destination(dest)

    if @subscription.save

#########################################################################################

      # starting_position = 0

      # if self.start_destination.present?
      #   starting_postion = Destination.where(:name => self.start_destination).first.chronological_order
      # end
      #####################################################
      starting_position = 1
      months = @subscription.months_subscribed
      dest_list = Destination.where("chronological_order >= ?", starting_position).order(chronological_order: :asc).limit(months)
##############################################################################
    
      dest_list.each do |dest|
        @subscription.add_destination(dest)
      end
      
      flash[:notice] = "Subscription saved."
      # redirect_to new_subscribe_path
      redirect_to current_user #skip payment for test
    else
      flash[:error] = "Error saving subscription. Try again."
      render :new
    end
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    name = @subscription.name


    
    if @subscription.destroy
      flash[:notice] = "\"#{name}\" has been deleted."
      redirect_to current_user
    else
      flash[:error] = "Error deleting subscriptions."
      render :show
    end

  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :primary, :months_subscribed, :start_destination)
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_itinerary.html.erb
<div class="col-md-12">
    <h3>Your upcoming trip is as follows:</h3>
   
  </div>

app/views/subscriptions/new.html.erb
<h1>Subscribe to a Subscription</h1>

<div class="row">
   
  <div class="col-md-8">

    <%= form_for @subscription do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter Subscription Name" %>
      </div>

      <div class="form-group">
        <%= f.label :months_subscribed %>
        <%= f.number_field :months_subscribed, class: 'form-control', placeholder: "How many months" %>
      </div>
       
      <div class="form-group">
        <%= f.label :primary %> - Check if this is your primary subscription
        <%= f.check_box :primary, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

  </div>

  
</div>

app/views/subscriptions/show.html.erb


<div class="text-center large">

  <div class="col-md-12">
    
  </div>
  <div class="col-md-12">
    <h2><%= @subscription.name %></h2>
    <p>
      <% if @subscription.primary == true %><span class="text text-primary">Primary Subscription</span>
      <% elsif @subscription.primary == false %><span class="text text-danger">Gift Subscription</span><% end %>
    </p>
  </div>

  <div class="col-md-12">
    You are subscribed for: <% if @subscription.months_subscribed == nil %><span>0</span><% end %><%= @subscription.months_subscribed %> months.
  </div>

  <div class="col-md-12">
    ..................................................
  </div>

  <div class="col-md-12">
    <h3>Your Upcoming trips:</h3>
    <% @destinations.each do |dest| %>
      <div class="col-md-12">
        <%= dest.name %> - <%= dest.region %>
      </div>
    <% end %>
  </div>

  <div class="col-md-12">
    ...........
  </div>

  <div class="col-md-12">
    <div class="col-md-12">
    <%= link_to "Delete Subscription", [@subscription], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this subscription?' } %>
  </div>

  <div class="col-md-12">
    ...................................................................
  </div>

  <div class="col-md-12">
    <%= link_to "User Profile", current_user %>
  </div>

  <div class="col-md-12">
    <%= link_to "Start Travelling", new_subscription_path %>
  </div>



  <div class="col-md-12">
  </div>

</div>