config/routes.rb
MAST::Application.routes.draw do



  root to: 'welcome#index'
  
  devise_for :users


  resources :users, only: [:show]
  resources :subscriptions, only: [:index, :show, :new, :create, :destroy]
  resources :destinations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :subscribe, only: [:new, :create]

  resource :cart, only: [:create, :destroy, :show] do
    put 'add/:destination_id', to: 'carts#add', as: :add_to
    put 'remove/:destination_id', to: 'carts#remove', as: :remove_from
  end
  
  resources :purchases, only: [:new, :create]





end

app/models/destination.rb
class Destination < ActiveRecord::Base

  def users
  end

  # for cart
  def cart_action(current_user_id)
    if REDIS.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end
  #

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  respond_to :html, :js

  def index
    @destinations = Destination.all

  end
  
  def show
    @destination = Destination.find(params[:id])

    # for cart
    @cart_action = @destination.cart_action current_user.try :id
    #

  end
  
  def new
    @destination = Destination.new

  end
  
  def create
    @destination = Destination.new(destination_params)


    if @destination.save
      flash[:notice] = "Destination saved."
      redirect_to @destination
      else
      flash[:error] = "Error saving destination."
      render :new
    end
  end
  
  def edit
    @destination = Destination.find(params[:id])

  end
  
  def update
    @destination = Destination.find(params[:id])


    if @destination.update_attributes(destination_params)
      flash[:notice] = "Destination updated."
      redirect_to @destination
    else
      flash[:error] = "Error updating destination."
      render :edit
     end
   end

    def destroy
      @destination = Destination.find(params[:id])
      if @destination.destroy
        flash[:notice] = "Destination deleted." 
      else
        flash[:error] = 'Error deleting destination.' 
      end
      redirect_to destinations_path
    end

   private 

    def destination_params
      params.require(:destination).permit(:name,:region,:country,:released,:individual_price,:chronological_order,:created_at,:updated_at)
   end


end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/edit.html.erb


<h1>Edit Destination</h1>
<div class="row">
   
  <div class="col-md-8">

    <%= form_for @destination do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Destination Name" %>
      </div>
      <div class="form-group">
        <%= f.label :region %>
        <%= f.text_field :region, class: 'form-control', placeholder: "Region" %>
      </div>
      <div class="form-group">
        <%= f.label :country %>
        <%= f.text_field :country, class: 'form-control', placeholder: "Country" %>
      </div>
      <div class="form-group">
        <%= f.label :released %> - Check if destination has been released
        <%= f.check_box :released, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :individual_price %>
        <%= f.number_field :individual_price, class: 'form-control', placeholder: "Individual Price" %>
      </div>
      <div class="form-group">
        <%= f.label :chronological_order %>
        <%= f.number_field :chronological_order, class: 'form-control', placeholder: "Chronological order of destination" %>
      </div>
       
      

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

  </div>

app/views/destinations/index.html.erb

<div class="text-center large">


  <div class="col-md-12">
    <%= link_to "Create Destination", new_destination_path, class: 'btn btn-success' %>
  </div>


<% @destinations.each do |dest| %>
    <div class="col-md-12">
      <%= dest.chronological_order %> - <%= link_to dest.name, dest %> - $<%= dest.individual_price %>
    </div>
  <% end %>


  <div class="col-md-12">
  </div>


  <div class="col-md-12">
  </div>


  <div class="col-md-12">
  </div>
  
</div>

app/views/destinations/new.html.erb


<h1>Create Destination</h1>
<div class="row">
   
  <div class="col-md-8">

    <%= form_for @destination do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Destination Name" %>
      </div>
      <div class="form-group">
        <%= f.label :region %>
        <%= f.text_field :region, class: 'form-control', placeholder: "Region" %>
      </div>
      <div class="form-group">
        <%= f.label :country %>
        <%= f.text_field :country, class: 'form-control', placeholder: "Country" %>
      </div>
      <div class="form-group">
        <%= f.label :released %> - Check if destination has been released
        <%= f.check_box :released, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :individual_price %>
        <%= f.number_field :individual_price, class: 'form-control', placeholder: "Individual Price" %>
      </div>
      <div class="form-group">
        <%= f.label :chronological_order %>
        <%= f.number_field :chronological_order, class: 'form-control', placeholder: "Chronological order of destination" %>
      </div>
       
      

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

  </div>

app/views/destinations/show.html.erb

<div class="text-center large">

  <div class="col-md-12">
    <%= link_to "Edit Destination", edit_destination_path, class: 'btn btn-success' %>
  
    <%= link_to "Delete Destination", [@destination], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this destination?' } %>
  </div>

  <div class="col-md-12">
    <h2><%= @destination.country %></h2>
  </div>

  <div class="col-md-12">
    <h3>$<%= @destination.individual_price %></h3>
  </div>

  <div class="col-md-12">
    <h5>Name: <%= @destination.name %></h5>
  </div>

  <div class="col-md-12">
    Region: <%= @destination.region %>
  </div>

  <div class="col-md-12">
    Released?: <%= @destination.released %>
  </div>

  <div class="col-md-12">
    Chronological order: <%= @destination.chronological_order %>
  </div>

  <div class="col-md-12">
    .......................................................
  </div>
  
  <div class="col-md-12">

  </div>

</div>




<div class="col-md-12">
<% if current_user %>

  <%=link_to "", class: 'btn btn-info', data: {target: @cart_action, addUrl: cart_path(destination_id: @destination.id), removeUrl: cart_path(destination_id: @destination.id)} do%>

      <span><%=@cart_action%></span> Cart
      <i class="glyphicon glyphicon-shopping-cart"></i>

  <%end%>

<%end%>
  </div>