config/routes.rb
MAST::Application.routes.draw do



  root to: 'welcome#index'
  
  devise_for :users


  resources :users, only: [:show]
  resources :subscriptions, only: [:index, :show, :new, :create, :destroy]
  resources :destinations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :subscribe, only: [:new, :create]

  resource :cart, only: [:create, :destroy, :show] do
    put 'add/:destination_id', to: 'carts#add', as: :add_to
    put 'remove/:destination_id', to: 'carts#remove', as: :remove_from
  end
  
  resources :purchases, only: [:new, :create]





end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MAST</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="col-md-12 text-right">
    <% if current_user %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% end %>
  </div>

  <div class="col-md-12">
    <% if current_user %>
      <%= link_to "Profile", current_user %>
    <% end %>
  </div>

  <div class="col-md-12">
    <%= link_to "Destinations", destinations_path %>
  </div>

  <div class="col-md-12">
    <% if current_user %>
      <%= link_to "My Cart", cart_path %> - <span class="cart-count"><%=current_user.cart_count%></span> items
    <% end %>
  </div>



  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>